/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.contocorrent;

import static gui.contocorrent.fileManager.download;
import static gui.contocorrent.fileManager.upload;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.*;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import org.omg.SendingContext.RunTime;

/**
 *
 * @author Ousseni bara
 */
public class nuovoConto extends javax.swing.JFrame implements Serializable, ActionListener, WindowListener{

    private int id;
    private String proprietario;
    private double saldo,fido;
    private Vector vettore;
    private CC conto;
    private File f;
    fileManager fileManager;
    
    public nuovoConto() throws IOException, FileNotFoundException, ClassNotFoundException{
        initComponents();
        setResizable(false);
        setTitle("BARA BANK | WebJobs");
        InputStream myStream = modifyProprietario.class.getResourceAsStream("logo.png");
        BufferedImage myImg = ImageIO.read(myStream);
        setIconImage(myImg);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setId(0);
        setProprietario(null);
        setFido(0);
        setSaldo(0);
        f=new File("conti.bin");
        vettore=new Vector();
        conto = new CC();
        fileManager=new fileManager();
        if(f.exists())
        download(f, vettore);
    }
    
    public nuovoConto(int id,String proprietario,double fido, double saldo){
        setId(id);
        setProprietario(proprietario);
        setFido(fido);
        setSaldo(saldo);
    }


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getProprietario() {
        return proprietario;
    }

    public void setProprietario(String proprietario) {
        this.proprietario = proprietario;
    }

    public double getSaldo() {
        return saldo;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public double getFido() {
        return fido;
    }

    public void setFido(double fido) {
        this.fido = fido;
    }
    
    public Vector getVettore(){
        return this.vettore;
    }
    
    public File getFile(){
        return this.f;
    }
    /**
     * Creates new form nuovoConto
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nomeField = new javax.swing.JTextField();
        fidoField = new javax.swing.JTextField();
        saldoField = new javax.swing.JTextField();
        header = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel2.setText("NOME INTESTATARIO");

        jLabel3.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel3.setText("FIDO");

        jLabel4.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel4.setText("SALDO");

        idField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        idField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idFieldMouseClicked(evt);
            }
        });
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        nomeField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        nomeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeFieldMouseClicked(evt);
            }
        });

        fidoField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        fidoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fidoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fidoFieldMouseClicked(evt);
            }
        });
        fidoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidoFieldActionPerformed(evt);
            }
        });

        saldoField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        saldoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        saldoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saldoFieldMouseClicked(evt);
            }
        });

        header.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("BARA BANK");

        submit.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        submit.setText("REGISTRAMI!");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(saldoField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(idField))
                    .addComponent(submit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fidoField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(saldoField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fidoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidoFieldActionPerformed

    private void idFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFieldMouseClicked

    }//GEN-LAST:event_idFieldMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        boolean control=false;
        if(idField.getText().equals("")||!conto.isOnlyNum(idField.getText())||nomeField.getText().equals("")||!conto.isOnlyCharacter(nomeField.getText())||saldoField.getText().equals("")||!conto.isOnlyNum(saldoField.getText())||fidoField.getText().equals("")||!conto.isOnlyNum(fidoField.getText()))
        {
            JOptionPane.showMessageDialog(null, "ATTENZIONE! ALCUNI CAMPI NON SONO STATI ANCORA COMPILATI O I VALORI INSERITI NON SONO ACCETTABILI");
        }else{
            
            id=Integer.parseInt(idField.getText());
            for(int x=0;x<vettore.size()&&control!=true;x++)
            {
                if(((CC) vettore.elementAt(x)).getId()==id&&!vettore.isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "ATTENZIONE! ID GIA' ESISTENTE, SI PREGA DI INSERIRNE UN'ALTRO");
                    control=true;
                }
            }
            if(control==false){
            try {
               
                f.createNewFile();
                
                proprietario=nomeField.getText();
                saldo=Double.parseDouble(saldoField.getText());
                fido=Double.parseDouble(fidoField.getText());
                vettore.addElement(new CC (id,proprietario,fido,saldo));
            
                upload(f, vettore);
            } catch (Exception ex) {}
            JOptionPane.showMessageDialog(null, "REGISTRAZIONE EFFETTUATA CON SUCCESSO!");
            }

        }
    }//GEN-LAST:event_submitMouseClicked

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void nomeFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeFieldMouseClicked

    }//GEN-LAST:event_nomeFieldMouseClicked

    private void fidoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fidoFieldMouseClicked

    }//GEN-LAST:event_fidoFieldMouseClicked

    private void saldoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saldoFieldMouseClicked

    }//GEN-LAST:event_saldoFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    
    //eventi finestra
    public void windowIconified(WindowEvent e){}
    public void windowDeiconified(WindowEvent e){}
    public void windowActivated(WindowEvent e){}
    public void windowDeactivated(WindowEvent e){}
    public void windowOpened(WindowEvent e){}
    @Override
    public void windowClosed(WindowEvent e){this.dispose();}
    @Override
    public void windowClosing(WindowEvent e){this.dispose();}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fidoField;
    private javax.swing.JLabel header;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField saldoField;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
