/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.contocorrent;

import static gui.contocorrent.fileManager.download;
import static gui.contocorrent.fileManager.upload;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import javax.swing.JButton;
import javax.swing.JTextField;
import java.io.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Ousseni bara
 */
public class operazioni extends javax.swing.JFrame implements Serializable, ActionListener, WindowListener{
    private boolean control=false;
    private CC conto;
    private int id,i;
    private fileManager fileManager; 
    private nuovoConto conti;
    
    public operazioni() throws IOException, FileNotFoundException, ClassNotFoundException{
        initComponents();
        setResizable(false);
        setTitle("BARA BANK | WebJobs");
        InputStream myStream = modifyProprietario.class.getResourceAsStream("logo.png");
        BufferedImage myImg = ImageIO.read(myStream);
        setIconImage(myImg);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setId(0);
        i=0;
        fileManager=new fileManager();
        conto=new CC();
        conti=new nuovoConto();
        if(conti.getFile().exists())
            download(conti.getFile(), conti.getVettore());
    }
        
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public JButton getBtnId() {
        return btnId;
    }

    public void setBtnId(JButton btnId) {
        this.btnId = btnId;
    }

    public JButton getBtnPrelievo() {
        return btnPrelievo;
    }

    public void setBtnPrelievo(JButton btnPrelievo) {
        this.btnPrelievo = btnPrelievo;
    }

    public JButton getBtnVersa() {
        return btnVersa;
    }

    public void setBtnVersa(JButton btnVersa) {
        this.btnVersa = btnVersa;
    }

    public JTextField getChIdField() {
        return chIdField;
    }

    public void setChIdField(JTextField chIdField) {
        this.chIdField = chIdField;
    }

    public JTextField getPrelievoField() {
        return prelievoField;
    }

    public void setPrelievoField(JTextField prelievoField) {
        this.prelievoField = prelievoField;
    }

    public JTextField getVersamentoField() {
        return versamentoField;
    }

    public void setVersamentoField(JTextField versamentoField) {
        this.versamentoField = versamentoField;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chIdField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        versamentoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prelievoField = new javax.swing.JTextField();
        btnPrelievo = new javax.swing.JButton();
        btnVersa = new javax.swing.JButton();
        btnId = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("BARA BANK");

        jLabel2.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INSERISCI L'IDENTIFICATIVO DEL CONTO");

        chIdField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        chIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VERSAMENTO");

        versamentoField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        versamentoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRELIEVO");

        prelievoField.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        prelievoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnPrelievo.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        btnPrelievo.setText("CONFERMA");
        btnPrelievo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrelievoMouseClicked(evt);
            }
        });

        btnVersa.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        btnVersa.setText("CONFERMA");
        btnVersa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVersaMouseClicked(evt);
            }
        });

        btnId.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 24)); // NOI18N
        btnId.setText("CONFERMA");
        btnId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIdMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(ATTENZIONE! CONFERMARE ID PRIMA DI VERSARE O PRELEVARE)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(versamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVersa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(prelievoField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrelievo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVersa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prelievoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrelievo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdMouseClicked

        if(chIdField.getText().equals("")||!conto.isOnlyNum(chIdField.getText()))
        {
            JOptionPane.showMessageDialog(null, "ERRORE! L'IDENFIFICATIVO INSERITO NON E' VALIDO");
        }else{
            control=false;
            setId(Integer.parseInt(chIdField.getText()));
            
            //ora cerco se l'ID inserito esiste o meno
            for(int x=0;x<conti.getVettore().size()&&control!=true;x++)
            {
                if(((CC)conti.getVettore().elementAt(x)).getId()==getId()&&!conti.getVettore().isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "ID TROVATO! ORA SI PUO' PROCEDERE CON IL VERSAMENTO O IL PRELIEVO");
                    i=x;
                    control=true;
                }
            }
            if(control==false)
            {
                JOptionPane.showMessageDialog(null, "ID INESISTENTE! SI PREGA DI INSERIRE UN ID ESISTENTE O CREARE UN NUOVO CONTO PER QUELLO");
            }
        }
    }//GEN-LAST:event_btnIdMouseClicked

    private void btnVersaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVersaMouseClicked
       if(control==false)
       {
           JOptionPane.showMessageDialog(null, "ATTENZIONE! E' NECCESSARIO, PRIMA DI VERSARE, INSERIRE UN ID VALIDO");
       }else{
           if(versamentoField.getText().equals("")||!conto.isOnlyNum(versamentoField.getText()))
           {
               JOptionPane.showMessageDialog(null, "ERRORE! INSERIRE UN DATO VALIDO");
           }else{
                       ((CC)conti.getVettore().elementAt(i)).versa(Double.parseDouble(versamentoField.getText()));
                       try {
                           upload(conti.getFile(),conti.getVettore());
                       } catch (Exception ex) {}
                       JOptionPane.showMessageDialog(null, "VERSAMENTO EFFETTUATO CON SUCCESSO");
               
           }
       }
    }//GEN-LAST:event_btnVersaMouseClicked

    private void btnPrelievoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrelievoMouseClicked
        if(control==false)
       {
           JOptionPane.showMessageDialog(null, "ATTENZIONE! E' NECCESSARIO, PRIMA DI VERSARE O PRELEVARE, INSERIRE UN ID VALIDO");
       }else{
           if(prelievoField.getText().equals("")||!conto.isOnlyNum(prelievoField.getText()))
           {
               JOptionPane.showMessageDialog(null, "ERRORE! INSERIRE UN DATO VALIDO");
           }else{
                   if(((CC) conti.getVettore().elementAt(i)).getId()==getId()&&((CC)conti.getVettore().elementAt(i)).getSaldo()-Double.parseDouble(prelievoField.getText())>=((CC)conti.getVettore().elementAt(i)).getFido())
                   {
                       ((CC)conti.getVettore().elementAt(i)).preleva(Double.parseDouble(prelievoField.getText()));
                       try {
                           upload(conti.getFile(),conti.getVettore());
                       } catch (Exception ex) {}
                       JOptionPane.showMessageDialog(null, "PRELIEVO EFFETTUATO CON SUCCESSO");
                   }else{
                       JOptionPane.showMessageDialog(null, "ERRORE! NON E' POSSIBILE PRELEVARE PIU' DEL IL FIDO MASSIMO");
                   }
               
               
           }
       }
    }//GEN-LAST:event_btnPrelievoMouseClicked

        //eventi finestra
    public void windowIconified(WindowEvent e){}
    public void windowDeiconified(WindowEvent e){}
    public void windowActivated(WindowEvent e){}
    public void windowDeactivated(WindowEvent e){}
    public void windowOpened(WindowEvent e){}
    @Override
    public void windowClosed(WindowEvent e){this.dispose();}
    @Override
    public void windowClosing(WindowEvent e){this.dispose();}
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnId;
    private javax.swing.JButton btnPrelievo;
    private javax.swing.JButton btnVersa;
    private javax.swing.JTextField chIdField;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField prelievoField;
    private javax.swing.JTextField versamentoField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
