/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.contocorrent;
import static gui.contocorrent.fileManager.download;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Ousseni bara
 */
public class saldoMaggiore extends javax.swing.JFrame implements WindowListener{
    private fileManager fileManager; 
    private nuovoConto conti;
    /**
     * Creates new form saldoMaggiore
     */
    public saldoMaggiore() throws IOException, FileNotFoundException, ClassNotFoundException{
        initComponents();
        setResizable(false);
        setTitle("BARA BANK | WebJobs");
        InputStream myStream = modifyProprietario.class.getResourceAsStream("logo.png");
        BufferedImage myImg = ImageIO.read(myStream);
        setIconImage(myImg);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        display.setEditable(false);
        fileManager = new fileManager();
        conti=new nuovoConto();
        if(conti.getFile().exists()){
            download(conti.getFile(),conti.getVettore());
            showContiMaggiori();
        }else{
            display.setText("NON CI SONO CONTI DA MOSTRARE!");
        }
    }
    
    public void showContiMaggiori(){
       double deposito=((CC) conti.getVettore().elementAt(0)).getSaldo();
       int pos=0;
        if(!conti.getVettore().isEmpty()&&conti.getFile().exists()){
        for(int x=0;x<conti.getVettore().size();x++)
        {
            if(deposito<((CC) conti.getVettore().elementAt(x)).getSaldo()){
                deposito = ((CC) conti.getVettore().elementAt(x)).getSaldo();
                pos=x;
            }
        }
        }else{
            JOptionPane.showMessageDialog(null,"ERRORE! NON CI SONO CONTI DA MOSTRARE");
        }
        display.setText(((CC) conti.getVettore().elementAt(pos)).getId()+" "+((CC) conti.getVettore().elementAt(pos)).getProprietario()+" "+((CC) conti.getVettore().elementAt(pos)).getFido()+" "+((CC) conti.getVettore().elementAt(pos)).getSaldo()+"\r\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 36)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("BARA BANK");

        display.setColumns(20);
        display.setFont(new java.awt.Font("Brandon Grotesque Bold", 0, 18)); // NOI18N
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

        //eventi finestra
    public void windowIconified(WindowEvent e){}
    public void windowDeiconified(WindowEvent e){}
    public void windowActivated(WindowEvent e){}
    public void windowDeactivated(WindowEvent e){}
    public void windowOpened(WindowEvent e){}
    public void windowClosed(WindowEvent e){this.dispose();}
    public void windowClosing(WindowEvent e){this.dispose();}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea display;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
